import tensorflow as tf
print("##########################################")
print("#       start chatting ver. 1.0          #")
print("##########################################")



'''
This code is doing the following things 1 It takes input from user and clean it 
using clean text function 2 Then it splits the text into words and then converts 
each word to index using vocab dictionary If a word doesn\'t exist in vocab dictionary 
then we replace that with OUT token which is used for padding purpose
- generated by stenography autopilot [ 🚗👩‍✈️ ]
'''
inputs = [
    "It's really cold here.",
    "This is my life.",
    "His room is a mess"
]


chatbot = tf.saved_model.LoadOptions()
_ = chatbot.reply(tf.constant(inputs)) #warmup

try:
	temp = .6
	



	while not stop_condition :
		user_input = input("you : ")
		print(user_input)
		if user_input == '!q':
			print('bye')
			stop_condition = True
			exit()
		# if user_input == '!q':
		# 	print('bye')
		else:
			print("chatbot : ", chatbot.reply(tf.constant(user_input)) )
			print("\n")

except:
	print("sorry didn't got you , please type again :( ")



def main():
	...

if __name__=="__main__":
	
	main()
